/**
 * record.mjs — the normal form a conforming parser must produce.
 *
 * ## Why a normal form, and not "match our JSON"
 *
 * A conformance suite that demanded a competitor emit *our* envelope would be
 * asking them to become us. What a parser can be held to without adopting our
 * shape is the **facts**: which slices a file has, what architecture and word
 * size each is, the sections it declares with their addresses, the load commands
 * by name, and the symbol counts. This module fixes only those — a small, closed
 * set — and defines the normalisation that makes two parsers' answers comparable
 * (addresses as lowercase `0x` hex strings, section and command names verbatim).
 *
 * ## Where the expected values come from
 *
 * `conformance/cases.json` is generated by this project's reader, but the reader
 * is not the authority it is checked against: the fixtures in `test/fixtures/`
 * are built from scratch by `test/fixtures.mjs`, which asserts each one's
 * properties independently before writing it. So the chain is
 * hand-built corpus → reader → cases.json, and a parser that disagrees with
 * cases.json is disagreeing with a file whose bytes were chosen, not observed.
 *
 * @param {object} d the object `describe()` returns
 * @returns {object} the conformance record
 */

import { filetypeKey } from '../src/macho.mjs';

/** A BigInt or number address as a lowercase `0x` string, or null. */
const hex = (v) => (v == null ? null : `0x${BigInt(v).toString(16)}`);

/** Normalise one `describe()` result into the record other parsers match. */
export function normalize(d) {
  return {
    size: d.size,
    fat: d.fat,
    slices: d.slices.map((s) => ({
      arch: s.arch,
      bits: s.bits ?? null,
      readable: s.readable,
      filetype: s.readable ? filetypeKey(s.filetype) : null,
      uuid: s.uuid ?? null,
      text: s.textAddr != null ? { addr: hex(s.textAddr), size: s.textSize } : null,
      symbols: { total: s.nsyms, defined: s.defined },
      sections: s.sections.map((x) => ({
        segname: x.segname,
        sectname: x.sectname,
        addr: hex(x.addr),
        size: x.size,
      })),
      loadCommands: s.loadCommands.map((c) => c.name),
    })),
  };
}
